theme: jekyll-theme-minimal
title: James Brady's CSS 155 homepage
description: Welcome to my first Github web page! Isn't this so cool?!
#This is a large header!
I wonder if we can go smaller?
###This is a smaller header!
__WOAH!__ I think we went too small....
##This is a perfecter header!
<sup>Aaa</sup>aaa<sub>ahh</sub>... That's _Juuust_ right!
